name: Emballageslm
favicon: null
layout_spectrum: 0.823787986766547
typography_spectrum: 0.9453540232498199
title: Emballages LM Packaging
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272727'
    - '#414141'
    - '#ffffff'
    - '#a0a0a0'
    - '#cccccc'
  brandStrength: 0.7612454174086452
  lightness: 0.24542271066457033
  saturation: 0.1746397870592773
  rhythmicContrast: 0.7697625998407602
purpose: []
